language: python

python:
  - '3.8'
  - '3.7'
  - '3.6'
  - '3.5'
  - '3.4'
  - '2.7'

install:
  - pip install tox-travis

script: tox

jobs:
  include:
    - stage: test
      name: pep8
      python: 3.8
      script: tox -e pep8
    - name: latest
      python: 3.8
      script: tox -e latest

    - stage: deploy
      python: 3.8
      script: skip
      deploy:
        provider: pypi
        user: internaphosting
        password:
          secure: fZxfMePJQroeiLQb+lmpNiEEMvRONOVt4yTQY8CmemyVMOe4TVZUfsBzCMa7eZkUaFZuHfNaUo/4Jmhn15EruzGhqBLRe5fpuFxFqJqDJ7ZmPMTRBIMKUsRuYrG6vc9YmG8CLfLvxwG8OUoLzND+rz+QwWaFruFeDlkCN3xMpzRHcdopcKlKoKwUJCkPzqEm0qeziTsRNixLbrBHzfr+FY96FDclE2GDywUBCacPzwP+R9QwPKU74NevlD+MazP/bYcZHY8DKDQ2X4L7NSr/8osJswVvCCoOqqqFPsPLaVzhDLU1hvTSW44K3hUSlRmKWzmdfFutkPix4Zrge9JYzTOodV921WgFLSsSPcpwEoRMZM21hoFhO6PThd9ag33z1rUxXzAJxBYfjM5OP+2g6gqWDptyJp8OgdqjzoCKFsXBrINf+vb+Ossdtl2+W1fzBjHlV9D8t6gf7ekJZmTAKzfYcvrRc++gnZwlwmPWrr5qBUSxT9SEqln7L/u4RbHxZdAOzYivPBvrL1ncdwUx9kvzbelr1wolc0aszodRgx8S7aWZ7V4CbuE6LpNkRREJ+EY71MYInpCRO81XabAIEG7T7i11ZkNexxQAe5Mafy/nSw5cGWirIAcLEO7WU3tSd5rteP7hgp28VJ9XfGZPwH9Q1FqiNMpKk+Db6PwplDE=
        on:
          tags: true
          distributions: sdist bdist_wheel
          repo: internap/python-ubersmithclient
  allow_failures:
    - name: latest
